import path from "node:path";
import fs from "node:fs/promises";
import { parseArgs } from "./args.js";
import { resolveConfig } from "./config.js";
import { runInstall } from "./install.js";
import { validateInstallation } from "./validate.js";
import { checkForUpdate, performSelfUpdate } from "./selfUpdate.js";
import { DEFAULT_PLACEHOLDERS } from "./constants.js";

const USAGE = `sf-ai-pack <command> [options]

Commands:
  init-config   Write a .sf-ai-pack.env preset file in the target project
  install       Install .github/.claude AI adoption assets (offline, no overwrite by default)
  update        Re-apply current placeholder values to already-installed assets,
                and optionally check/install a newer published version of this CLI
  validate      Scan installed assets for unresolved {{PLACEHOLDER}} tokens

Common options:
  --target github|claude|both
  --project-dir <path>
  --env-file <path>
  --merge-strategy skip|overwrite|backup|fail
  --dry-run

Update-only options:
  --self-update            Install the latest published CLI version globally
  --skip-version-check     Skip the registry lookup and only refresh templates

See README.md for the full list of placeholder override flags.`;

export async function runCli(argv) {
  const [command, ...rest] = argv;

  if (!command || command === "--help" || command === "-h") {
    console.log(USAGE);
    return 0;
  }

  try {
    switch (command) {
      case "init-config":
        return await handleInitConfig(rest);
      case "install":
        return await handleInstall(rest);
      case "update":
        return await handleUpdate(rest);
      case "validate":
        return await handleValidate(rest);
      default:
        console.error(`Unknown command: ${command}\n\n${USAGE}`);
        return 1;
    }
  } catch (err) {
    console.error(`sf-ai-pack: ${err.message}`);
    return 1;
  }
}

async function handleInitConfig(rest) {
  const cliArgs = parseArgs(rest);
  const projectDir = path.resolve(cliArgs.flags.projectDir || ".");
  const envPath = path.join(projectDir, ".sf-ai-pack.env");

  const lines = [
    "# sf-ai-pack preset configuration",
    "# Generated by: sf-ai-pack init-config",
    `TARGET=${cliArgs.flags.target || "both"}`,
    `MERGE_STRATEGY=${cliArgs.flags.mergeStrategy || "skip"}`,
    ...Object.entries({ ...DEFAULT_PLACEHOLDERS, ...cliArgs.placeholders }).map(
      ([key, value]) => `${key}=${value}`,
    ),
  ];

  await fs.mkdir(projectDir, { recursive: true });
  await fs.writeFile(envPath, lines.join("\n") + "\n");
  console.log(`Wrote preset configuration to ${envPath}`);
  return 0;
}

async function handleInstall(rest) {
  const cliArgs = parseArgs(rest);
  const config = await resolveConfig({ cliArgs });
  const results = await runInstall(config);
  reportResults(results, config, "installed");
  return 0;
}

async function handleUpdate(rest) {
  const cliArgs = parseArgs(rest);

  if (!cliArgs.skipVersionCheck) {
    const info = await checkForUpdate();
    if (info.error) {
      console.log(
        `Could not check the registry for a newer version (${info.error}). Continuing with the currently installed templates.`,
      );
    } else if (info.updateAvailable) {
      console.log(
        `A newer version is available: ${info.name}@${info.latestVersion} (installed: ${info.currentVersion}).`,
      );
      if (cliArgs.selfUpdate) {
        console.log(`Running: npm install --global ${info.name}@latest ...`);
        await performSelfUpdate({ name: info.name, registry: info.registry });
        console.log(
          'Global package updated. Run "sf-ai-pack update" again to apply the refreshed templates from the new version.',
        );
        return 0;
      }
      console.log(
        'Re-run with --self-update to install it now, then run "update" again to refresh templates.',
      );
    } else {
      console.log(
        `Already on the latest published version (${info.currentVersion}).`,
      );
    }
  }

  // Re-render installed assets with the current placeholder values. Unlike
  // `install`, existing template-managed files are refreshed by default,
  // ignoring any MERGE_STRATEGY stored from a prior install/init-config.
  const config = await resolveConfig({
    cliArgs,
    defaultMergeStrategy: "overwrite",
    honorStoredMergeStrategy: false,
  });
  const results = await runInstall(config);
  reportResults(results, config, "refreshed");
  return 0;
}

async function handleValidate(rest) {
  const cliArgs = parseArgs(rest);
  const config = await resolveConfig({ cliArgs });
  const { findings, isClean } = await validateInstallation({
    projectDir: config.projectDir,
    target: config.target,
  });

  if (isClean) {
    console.log("No unresolved placeholders found.");
    return 0;
  }

  for (const finding of findings) {
    console.log(
      `${finding.file}:${finding.line}  unresolved placeholder {{${finding.token}}}`,
    );
  }
  console.error(`\n${findings.length} unresolved placeholder(s) found.`);
  return 1;
}

function reportResults(results, config, verb) {
  for (const [target, result] of Object.entries(results)) {
    if (target === "envExample") continue;
    console.log(
      `\n[${target}] ${verb}: ${result.written.length}, skipped: ${result.skipped.length}, backed up: ${result.backedUp.length}, merged: ${result.merged.length}`,
    );
  }
  if (results.envExample) {
    const env = results.envExample;
    console.log(
      `\n[.sf-ai-pack.env.example] ${verb}: ${env.written.length}, skipped: ${env.skipped.length}, backed up: ${env.backedUp.length}`,
    );
  }
  if (config.dryRun) console.log("(dry-run — no files were changed)");
}
