import fs from "node:fs/promises";
import path from "node:path";
import { resolveWithinRoot } from "./security.js";

export const PRESET_FILE_NAME = ".sf-ai-pack.env";

function formatValue(value) {
  const str = String(value);
  const needsQuotes =
    /^\s|\s$/.test(str) ||
    str.includes(" #") ||
    ((str.startsWith('"') || str.startsWith("'")) && str.length > 0);
  if (!needsQuotes) return str;
  return str.includes('"') ? `'${str}'` : `"${str}"`;
}

/**
 * Persists values passed on the command line to <projectDir>/.sf-ai-pack.env
 * so later `update` runs reuse them. If the file does not exist it is created
 * with every resolved value; if it exists, only the passed keys are changed in
 * place (missing ones are appended) and all other lines are left untouched.
 */
export async function persistPreset({
  projectDir,
  values,
  fullValues,
  dryRun,
}) {
  const result = { created: false, updated: [], added: [] };
  if (Object.keys(values).length === 0) return result;

  const destPath = resolveWithinRoot(projectDir, PRESET_FILE_NAME);
  let existing = null;
  try {
    existing = await fs.readFile(destPath, "utf8");
  } catch (err) {
    if (err.code !== "ENOENT") throw err;
  }

  if (existing === null) {
    const lines = [
      "# sf-ai-pack preset configuration",
      "# Generated by: sf-ai-pack install",
      ...Object.entries(fullValues).map(
        ([key, value]) => `${key}=${formatValue(value)}`,
      ),
    ];
    result.created = true;
    result.added = Object.keys(fullValues);
    if (!dryRun) {
      await fs.mkdir(projectDir, { recursive: true });
      await fs.writeFile(destPath, lines.join("\n") + "\n");
    }
    return result;
  }

  const pending = new Map(Object.entries(values));
  const lines = existing.split(/\r?\n/).map((line) => {
    const eqIdx = line.indexOf("=");
    if (eqIdx === -1 || line.trim().startsWith("#")) return line;
    const key = line.slice(0, eqIdx).trim();
    if (!pending.has(key)) return line;
    const next = `${key}=${formatValue(pending.get(key))}`;
    pending.delete(key);
    if (next !== line) result.updated.push(key);
    return next;
  });

  while (lines.length > 0 && lines[lines.length - 1] === "") lines.pop();
  for (const [key, value] of pending) {
    lines.push(`${key}=${formatValue(value)}`);
    result.added.push(key);
  }

  if (!dryRun && (result.updated.length > 0 || result.added.length > 0)) {
    await fs.writeFile(destPath, lines.join("\n") + "\n");
  }
  return result;
}

/**
 * Appends any of `entries` that are not already listed to
 * <projectDir>/.gitignore, creating the file when needed.
 */
export async function ensureGitignore({ projectDir, entries, dryRun }) {
  const result = { created: false, added: [] };
  const destPath = path.join(projectDir, ".gitignore");

  let existing = null;
  try {
    existing = await fs.readFile(destPath, "utf8");
  } catch (err) {
    if (err.code !== "ENOENT") throw err;
  }

  const normalize = (line) => line.trim().replace(/^\//, "").replace(/\/$/, "");
  const present = new Set(
    (existing ?? "")
      .split(/\r?\n/)
      .filter((line) => line.trim() && !line.trim().startsWith("#"))
      .map(normalize),
  );

  result.added = entries.filter((entry) => !present.has(normalize(entry)));
  result.created = existing === null && result.added.length > 0;
  if (result.added.length === 0 || dryRun) return result;

  const prefix =
    existing === null || existing === ""
      ? ""
      : existing.endsWith("\n")
        ? "\n"
        : "\n\n";
  const block = `# AI assistant assets (sf-ai-pack)\n${result.added.join("\n")}\n`;
  await fs.mkdir(projectDir, { recursive: true });
  await fs.writeFile(destPath, (existing ?? "") + prefix + block);
  return result;
}
